sources:
  dtek.ical:
    type: "ical"
    url: "https://calendar.google.com/calendar/ical/dtek.se_0tavt7qtqphv86l4stb0aj3j88%40group.calendar.google.com/public/basic.ics"
    pattern: "lunch|föreläsning|föreläs|gratis|lunchföreläsning"
