sources:
  dtek.ical:
    type: "ical"
    url: "https://calendar.google.com/calendar/ical/dtek.se_0tavt7qtqphv86l4stb0aj3j88%40group.calendar.google.com/public/basic.ics"
    icon_url: "https://pbs.twimg.com/profile_images/834837895441694721/3kIStwdu_400x400.jpg"
    pattern: "lunch|föreläsning|föreläs|gratis|lunchföreläsning"

  it.ical:
    type: "ical"
    url: "https://calendar.google.com/calendar/ical/a55ipd3o49n05cd2eebqo854qs%40group.calendar.google.com/public/basic.ics"
    icon_url: "https://scontent.fmmx4-1.fna.fbcdn.net/v/t39.30808-1/308674774_463067489183780_8436292654341922861_n.jpg?stp=dst-jpg_p200x200&_nc_cat=101&ccb=1-7&_nc_sid=c6021c&_nc_ohc=NRg4sOTq9mEAX9xopgc&_nc_ht=scontent.fmmx4-1.fna&oh=00_AfBxd4GtUJVeeFhaQs1q-D_wf4BaNUypzA7XwImKQeizew&oe=638EF9AF"
    pattern: "lunch|föreläsning|föreläs|gratis|lunchföreläsning"
